spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fantomfite_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cjy123456
server:
  port: 8182
mybatis:
  mapper-locations: classpath:mapper/*/*.xml